# Generated by Django 3.2.8 on 2021-10-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='delaapp.image'),
        ),
    ]
