# Generated by Django 3.2.8 on 2021-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delaapp', '0002_alter_comment_postde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='delaapp.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile.jpg', upload_to='profiles/'),
        ),
    ]
