# Generated by Django 3.2.8 on 2021-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delaapp', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile.jpg', upload_to='profiles/'),
        ),
    ]
